### ISSUE TITLE
Formatting of JSON  in Response (FI-1542)

### ISSUE THREAD

**Issue by BSpassky93** [onc-healthit/onc-certification-g10-test-kit#106]
Hi,

I have recently upgraded to using the new version of Inferno for local testing. The UI is generally an improvement, however, the way that the JSON is displayed in the response is a downgrade from the previous version. Could someone point me to where I could add formatting to the response body. I have been looking in the inferno_core-0.3.1 gem, which seems reasonable as to where these files live. 
![Screenshot_23](https://user-images.githubusercontent.com/34255863/164553054-42935c6e-dea9-4613-89cb-d83ffc422678.png)

**Comment by chris-at-work** [comment]
@BSpassky93 It's [here](https://github.com/inferno-framework/inferno-core/blob/main/client/src/components/RequestDetailModal/CodeBlock.tsx#L16) as source but the gem includes minified javascript so you wouldn't see it plainly if you looked inside the gem.

But we can improve this to be a formatted document style thing with many lines instead of an unreadable single line.
