### ISSUE TITLE
DocumentReference content.attachment.contentType

### ISSUE THREAD

**Issue by Sanvenky** [onc-healthit/onc-certification-g10-test-kit#115]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/38855381/165923790-f0b64936-b4a7-4024-920d-3e1eb3b717e3.png">

When some of the DocumentReference ids are not resolved by binary, we are not populating the binary content.attachment.url and content.attachment.contentType. We are populating the unsupported DAR for contentType and url.
But inferno test **10.10** is failing with error "DocumentReference.content[0].attachment.contentType: No code provided, and a code is required from the value set" .
It is looking for contentType code from value set. But we are raising unsupported DAR. 
Is this an issue in the Inferno tests or looking for contentType code from value set?

http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-documentreference.html

```
"content": [
        {
            "attachment": {
                "_contentType": {
                    "extension": [
                        {
                            "valueCode": "unsupported",
                            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
                        }
                    ]
                },
                "_url": {
                    "extension": [
                        {
                            "valueCode": "unsupported",
                            "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
                        }
                    ]
                }
            }
        }
    ]
```

**Comment by yunwwang** [comment]
`DocumentReference.content.attachment.contentType` has a `code `data type with required binding
![image](https://user-images.githubusercontent.com/8761175/165951224-855e86a5-9bad-4611-b659-75db40f1588c.png)

According to the US Core General Guidance Missing Data Section (http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#missing-data), a coded data element with required binding must use the appropriate “unknown” concept code from the value set if available. Since there is not appropriate "unknown" concept code in BCP-47, a system must use an appropriate code instead of DAR extension.

The intention from US Core author is that DocumentReference resource must have attachments and such attachment must have contentType. It is not reasonable to create a DocumentReference resource without content/attachment.

**Comment by Sanvenky** [comment]
Thanks.
