### ISSUE TITLE
Issue with Multi Patient API test 5.2.05 for status

### ISSUE THREAD

**Issue by GregmarC** [onc-healthit/onc-certification-g10-test-kit#132]
<img width="1440" alt="Screen Shot 2022-05-18 at 4 37 46 PM" src="https://user-images.githubusercontent.com/49351487/169152668-55a61ad8-7385-431e-8b21-d8e7997232cc.png">

We are experiencing an issue with this part of the test (e.g. 5.2.05). We have tested on our bulk fhir server and we are responding with the correct response well within the allotted time. Though the screenshot states "The server took more than 180 seconds," it was actually the tool that took too long to send the request itself. Once the request was received our server responds in less than 7 seconds. Additionally, the expected response is valid (e.g. 202 Accepted).

**Comment by yunwwang** [comment]
@GregmarC Thank you for reaching to us. 

First, the 180 second is the default timeout value. You can adjust that before you start the testing. See the screenshot
![image](https://user-images.githubusercontent.com/8761175/169169503-ce886035-ab16-484b-93d0-36e8463ae82a.png)

Second. This is how Inferno calculate the wait time.
If your server provide `retry-after` in header, as specified [here](http://hl7.org/fhir/uv/bulkdata/STU1.0.1/export/index.html#endpoint-1), Inferno will use that value as wait time. If your server does not specify `retry-after` value, Inferno will use exponential back-off to calculate the wait time. The exponential back-off value is `2 ** n - 1`, or 1, 3, 7, 15, 31, 63, 127, ....

Finally, how Inferno decide if the status check reaches timeout threshold. Inferno adds the wait time (specified in #2) to current elapsed time. If the sum is greater than the timeout value  (specified in #1), then inferno decides the request is a time out.

For example, using the exponential back-off and default timeout value, Inferno will timeout after
1 + 3 + 7 + 31 + 63 = 105 second. Because the next wait time is 127 seconds and 105+127 > 180.

Another example, server returns `retry-after: 50`. Inferno will timeout after 
50 + 50 + 50 = 150 seconds. 

The last example, server return 'retry-after: 200`. Inferno will timeout after the first status check. Because 0 (current elapsed time) + 200 (wait time) > 180.

Please double if your server returns correct `retry-after` value and if you need to increase the timeout threshold.

**Comment by GregmarC** [comment]
<img width="1440" alt="Screen Shot 2022-05-19 at 1 31 43 PM" src="https://user-images.githubusercontent.com/49351487/169362884-443a4a6d-daf0-431b-97a6-0454be2afbcc.png">


<img width="1440" alt="Screen Shot 2022-05-19 at 1 31 24 PM" src="https://user-images.githubusercontent.com/49351487/169362915-414a50ec-f788-4215-b82c-7d5bba74c87d.png">



Thank you for the prompt response. I changed the time out time to 600 seconds to give a maximal amount of time for the export to succeed. I am still having an issue where the tool "claims" that the server took too long to respond.

Once again, as shown in the pictures above, I am able to obtain the appropriate response from my local server in 1.3s when I test the polling location myself with a GET request through postman. 

What "seems" to be the issue is that the local inferno tool is taking too long to send the request out itself and then claims the server took too long to respond. Any further thoughts or suggestions?


-Best

**Comment by yunwwang** [comment]
Can you run a test on inferno.healthit.gov so I can check the session data?

**Comment by yunwwang** [comment]
I think I see the issue. 202 means "in-progress". when the export is complete, server need return 200

See: http://hl7.org/fhir/uv/bulkdata/STU1.0.1/export/index.html#response---complete-status

**Comment by GregmarC** [comment]
Yes, I actually just discovered this by investigating the source code just minutes before your latest response. It did the trick. 

Thank you very much for you help!

**Comment by yunwwang** [comment]
Hello @GregmarC  

I will close this issue as no activities over the last few months. If you experience similar issue in the future, you can reopen this issue or create a new one. 

Thank you
