### ISSUE TITLE
Ability to export results into CSV or EXCEL

### ISSUE THREAD

**Issue by MTroianov** [onc-healthit/onc-certification-g10-test-kit#144]
Hello!
Our team is looking for the best way to store results of the profile runs for tracking purposes, how would you recommend to do it in this version?
Previously, we were using 'save results' which we were able to retrieve later by hashed link, but now I can't find this option in the UI.
I also tried looking into generated SQLITE db directly, but I haven't found clear indication of how to create a relation between results and the profile/test run.
Thanks in advance!

**Comment by Jammjammjamm** [comment]
All the `save results` button did was display the url from the address bar in a modal. You can just copy the url from your browser's address bar for the same effect.

If you want the results in a machine-readable format, I'd recommend using the [JSON API](https://inferno-framework.github.io/inferno-core/api-docs/) over directly querying the db. When you're using Inferno, your url will look like:
`HOST_AND_BASE_PATH/test_sessions/TEST_SESSION_ID#GROUP_ID`
You can get the results for a session as JSON by performing a GET to:
`HOST_AND_BASE_PATH/api/test_sessions/TEST_SESSION_ID/results`
If there is additional functionality that would be helpful in the JSON API, please let us know and we will consider adding it.

You're really looking for the results of a test session, rather than a test run. Any time you click a run button in inferno, a new test run is created. So a single test session can contain multiple test runs together.

**Comment by MTroianov** [comment]
Thanks for very descriptive response! 
I might be getting some questions while testing the JSON API that you shared, but it looks very useful to our needs at the first glance.

**Comment by MTroianov** [comment]
Sorry, one more question. Is there a way to install Inferno with US Core 4.0.0 locally?

**Comment by Jammjammjamm** [comment]
Sure, if you don't want the g10 tests, you can just clone and run the [US Core Test Kit](https://github.com/inferno-framework/us-core-test-kit).

If you want the g10 tests to be available, too, I'm pretty sure you just need to:
- [replace this line](https://github.com/onc-healthit/onc-certification-g10-test-kit/blob/main/lib/onc_certification_g10_test_kit.rb#L2) with just `require 'us_core_test_kit'`.
- place the [US Core 4.0.0 IG package](https://hl7.org/fhir/us/core/STU4/package.tgz) in `lib/onc_certification_g10_test_kit/igs`. You'll need to rename it since there's already a `package.tgz` there.

**Comment by MTroianov** [comment]
Our team is concentrated on compliance of Single Patient API with US Core 4.0.0, did I get it correctly that we can use US Core Test Kit with 4.0.0 selected for that?

**Comment by Jammjammjamm** [comment]
Yes.

**Comment by MTroianov** [comment]
Thanks for help!
