### ISSUE TITLE
US Core V3.1.1 Smoking Status Observation Tests 14.08 error on effectiveDateTime

### ISSUE THREAD

**Issue by healthland** [onc-healthit/onc-certification-g10-test-kit#165]
Expecting since this is V3.1.1 that the effectivePeriod would be valid.  

https://www.hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-smokingstatus.html

![2022-07-13 13_37_54-Inferno](https://user-images.githubusercontent.com/66788141/178807021-bb8eda7b-ca4b-49ba-a614-6bfce6e70b07.png)

**Comment by yunwwang** [comment]
@healthland

Thank you for reach to us. We also noticed this problem after introducing US Core 4.0.0 Test Kit. The issue is that US Core 3.1.1 Test Kit validates using US Core 4.0.0 profile. We are working on the fix of that.

**Comment by healthland** [comment]
Thank you for confirming what we thought we were seeing as an issue.  Thanks for working on a fix.  Thanks!

**Comment by yunwwang** [comment]
Reopen for release process

**Comment by nathanloyer** [comment]
Hey all,

With regards to the update to the us-core-test-kit, I thought the root cause of this issue was that the FHIR validator couldn't have multiple versions of the same IG loaded at once. Has that issue been resolved in the hapi fhir validator? Or I suppose the better question is: have you confirmed that adding the profile version to the request to the FHIR Validator actually uses the correct profile version?

**Comment by Jammjammjamm** [comment]
> have you confirmed that adding the profile version to the request to the FHIR Validator actually uses the correct profile version?

Yes, we have confirmed this. There are caveats (I can provide more details if you want), but none that should affect US Core. This functionality is in `main` in the US Core test kit (not yet in an official release), so you can test it out there. As a simple spot check, our reference server is loaded with 3.1.1 data, and the Smoking Status observations fail validation against the 4.0.0 profile. You can verify that they pass in 3.1.1 but fail in 4.0.0.
