### ISSUE TITLE
Running inferno test with new version: ONC Certification (g)(10) Standardized API V.2.2.2 - causes new test failure

### ISSUE THREAD

**Issue by MothyTim** [onc-healthit/onc-certification-g10-test-kit#166]
@arscan Here is information requested:

Test 5.3.1.8 Encounter Resources returned conform to the US Core Encounter Resource Profile

Encounter.participant[0].type[0].coding[0]: Unknown Code http://terminology.hl7.org/CodeSystem/participant-type#PART in http://terminology.hl7.org/CodeSystem/participant-type for 'http://terminology.hl7.org/CodeSystem/participant-type#PART'

{"resourceType":"Encounter","id":"143403831","meta":{"profile":["http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter"]},"identifier":[{"use":"official","system":"http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter","value":"143403831"}],"status":"finished","class":{"system":"http://terminology.hl7.org/CodeSystem/v3-ActCode","code":"AMB","display":"ambulatory"},"type":[{"coding":[{"system":"http://www.ama-assn.org/go/cpt","code":"99201","display":"Office Visit"}],"text":"Office Visit"}],"subject":{"reference":"Patient/387851059"},"participant":[{"type":[{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/participant-type","code":"PART","display":"Participation"}],"text":"Participation"}],"period":{"start":"2022-06-15T13:53:19-07:00","end":"2022-06-15T14:32:07-07:00"},"individual":{"reference":"Practitioner/2893672"}}],"period":{"start":"2022-06-15T13:53:19-07:00","end":"2022-06-15T14:32:07-07:00"},"reasonCode":[{"text":"No reason provided."}],"hospitalization":{"dischargeDisposition":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/discharge-disposition","code":"oth","display":"Other"}],"text":"Other"}},"location":[{"location":{"reference":"Location/1884466"}}]}

Let me know if you need anything else. 

Regards, Tim

**Comment by MothyTim** [comment]
This issue is fixed by developer in product being tested.

**Comment by arscan** [comment]
Hi @MothyTim -- FYI that we also figured out that our inferno.healthit.gov deployment did not update one of its dependencies properly when we deployed v2.2.2 this week (a problem very specific to inferno.healthit.gov), which may have been why this failure started occurring for you.  We fixed the issue last night.  See this related ticket, where another user was having a similar problem: https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/167

For most cases, the failure isn't helpful because it happens when the validator doesn't know about a CodeSystem, but the system is allowed to use it due to the binding strength of the element.  It sounds like perhaps in this case the error was helpful to your developer though.
