### ISSUE TITLE
Modified scope is not carried forward to the appropriate section (FI-1639)

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/onc-certification-g10-test-kit#170]
Inferno defaults the following scope on the Standalone Patient App - Full Access input screen:
 launch/patient openid fhirUser offline_access patient/*.read
The first issue is that not all FHIR resources can use patient/*.read, for example scope for the  Organization resource should be user/Organization.read. But, the most important is that when scope is modified it is not carried forward to the next appropriate series of tests. Here is an example. 
Using Inferno Reference Server modify scope on the Standalone Patient App - Full Access input screen as follows:

launch/patient openid fhirUser offline_access patient/AllergyIntolerance.read patient/CarePlan.read patient/CareTeam.read patient/Condition.read patient/Device.read patient/DiagnosticReport.read patient/DocumentReference.read patient/Encounter.read patient/Goal.read patient/Immunization.read patient/MedicationRequest.read patient/Observation.read user/Organization.read patient/Patient.read user/Practitioner.read patient/Procedure.read patient/Provenance.read user/Person.read
Run the Standalone Patient App - Full Access series of tests. Navigate to Standalone Patient App - Limited Access. Select Run Tests and observe that the default scope values are displayed instead of the modified scope entered before.

**Comment by arscan** [comment]
Thanks for logging a ticket for the suggestion to carry forward the scopes to the Limited Access test.  I believe that prior to v2.0 we did it in the way you are suggesting.  There may be a technical reason why we decided to not do that in v2.0+, but it could just be an oversight.  We are looking into it.

Regarding the other point:

> The first issue is that not all FHIR resources can use patient/\*.read, for example scope for the Organization resource should be user/Organization.read. 

This is an implementation decision to be made by the server.  `patient/Organization.read` could grant access to those Organizations needed to make sense of the patient's compartment, even if though the Organization resource does not have a direct reference to the patient (a couple of hops would be involved). We defaulted to this approach because we are testing the [permission-patient](http://hl7.org/fhir/smart-app-launch/1.0.0/conformance/index.html#permissions) core capability in this scenario, but we allow systems to change that to user/Organization.read if they have chosen the more literal approach where patient/\*.read scopes only apply to resources that have a direct patient reference in them.

There have been a couple of conversations about this on Zulip (it is certainly a point of confusion) -- one example is here: https://chat.fhir.org/#narrow/stream/179170-smart/topic/patient.2F*.2E*

Does this clear up that issue for you?

And we'll let you know if we can update that scope carry-forward issue.  Thanks!

**Comment by arscan** [comment]
Looks like it shouldn't be a problem to address and this was just an oversight.  Thank you very much for this report, we'll try to get it in the next version.

Also, this is more than just a convenience thing.  Our intent for this test was for the second launch to be with an app that makes the exact same authorization request as the first launch, but shows that the user can be given control to deny the app access to some, but not all requested scopes (as required by the rule).  By allowing the tester to fill in completely different scopes for the request we are instead potentially showing that an app can be configured to request fewer scopes, vs having the user approve/deny scopes, which is not the same thing.
