### ISSUE TITLE
Inferno tests which were passing earlier now failing for all resources with organization.identifier.type.system - unknown system

### ISSUE THREAD

**Issue by mamataT** [onc-healthit/onc-certification-g10-test-kit#206]
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Inferno Certification tests, Single Patient API now failing for all resources which has reference to Organization. These were passing earlier, so not sure if Inferno has changed anything.

**Your environment**
FHIR End point: https://fhirtest.fhirpointtest.open.allscripts.com/fhirroute/fhir/INFFP01

* Edition of inferno (Community or Program):
* Version of inferno:
* Which browser and version(s) is the bug present on?:
Chrom

**Steps to reproduce**
After running the Standardized API test#4 Single Patient API, all resources (Allergy, Condition, patient, observation etc) fails with error:

Example error from Patient resource:

Patient.managingOrganization.identifier.type.coding[0]. Unknown Code System "http://hl7.org/fhir/sid/us-npi"

However, looking at FHIR Spec v3.1.1 this is a fixed and valid system for organization.identifier.type

Include:

* The selected test suite - 10 Stardardized ATP - Test#4: Single Patient API - 4.2.08
* The URL of the FHIR server being tested: https://fhirtest.fhirpointtest.open.allscripts.com/fhirroute/fhir/INFFP01
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
ClientID: [removed]
Client Secret: [removed]

* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by arscan** [comment]
Hi @mamataT -- it seems like we missed this issue because it was posted in a repository that we weren't expecting (I have since added a notice so others don't make the same mistake).  I transferred it to [the right spot](https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/) (please post issues here in the future).

Do you still have this problem?  I'm unsure if you opened a separate issue here or on Zulip, so we may have already figured this one out.
