### ISSUE TITLE
US Core v 4.0.0 tests performing differently based on Patient ID order

### ISSUE THREAD

**Issue by jj027509** [onc-healthit/onc-certification-g10-test-kit#210]
I have two patient IDs that I use to perform my single patient tests. I have found that the patient I use to get the provider token must be the first listed patient id, otherwise the tests perform differently. 
Tests which see different outcomes: When the patient who was not used to authorize is listed first in the patient id field, 2.02, 2.061 and 10.02 skip. 10.08 fails. 

Test run where first listed patient id was used to generate provider token:
https://inferno.healthit.gov/suites/test_sessions/06060b54-ae95-4c51-b742-203fb59cf716#us_core_v400

Test run where second listed patient id was used to generate provider token: 
https://inferno.healthit.gov/suites/test_sessions/0740351d-451a-41c1-9dd3-6a8258d73532#us_core_v400

**Comment by yunwwang** [comment]
During the test, it is common that one patient may not have enough data covering all the test cases. So Inferno allows server to provide "additional" patients to cover those test cases not supported by the first patient. That is based on the precondition that server allows Inferno to read data for those "additional" patients.

To reduce the number of searches between Inferno and server, Inferno uses the resources returns from the the first search to form the search queries for the following searches. 

For example, for Patient test group, the first search is 2.01 "Patient search by _id". The following test 2.02 "Patient search by identifier" uses one identifier found in the Patient resources returned in 2.01 to form the search query.

In your testing sessions, there are two patient 4755812, 4755813. In both sessions, 4755812 is the one used to generate token. 

In your second test session, the patient 4755813 is listed first. What happened during the testing was that 2.01 searched `?_id=4755813` first because that is the first one in patient id list, followed by searching `?_id=4455812`. When executing test 2.02, Inferno looked the Patient resources from 2.01 and used the identifier from the first patient it found (Patient.id=4758813), to form the query `?identifier=197` for the identifier search. From the result, we know that server returned an empty Bundle indicating that patient with identifier 197 did not exist or could not be accessed by Inferno. That created a logic conflict that server confirmed the existence of patient with identifier 197 in test 2.01 but could not return the same patient in 2.02.

You may wondering why 2.03 passed. It happened to be that both patient have the same last name.

**Comment by jj027509** [comment]
@yunwwang  Thank you for the explanation - I really appreciate it!
