### ISSUE TITLE
US Core 4.0.0 Failing Condition Test 6.08 Unable to Resolve Value set

### ISSUE THREAD

**Issue by fpivonka** [onc-healthit/onc-certification-g10-test-kit#219]
In this test run https://inferno.healthit.gov/suites/test_sessions/13a61359-55f2-46d1-81da-0f4c67836cff#us_core_v400-us_core_v400_condition we are now seeing failures where the SNOMED-CT and ICD-10-CM codes say they are not valid in the us-core-condition-code valueset.   Example: 

 Condition/p6377467:  Condition.code: Error from server: Unable to resolve value set  "http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code\|4.0.0"

There are a couple of codes in our json response that are not valid codes such as codes from Intelligent Medical Objects (IMO) but those are always present as an additional code. I ran the example SNOMED and ICD codes through the terminology validator and they seem valid. Can you help us troubleshoot the issue? 

From the example above I ran SNOMED-CT code 386661006 through the validator and received the following:

http://tx.fhir.org/r4/ValueSet/us-core-condition-code/$validate-code?code=386661006&system=http://snomed.info/sct

`
{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "display",
            "valueString": "Fever (finding)"
        },
        {
            "name": "system",
            "valueString": "http://snomed.info/sct"
        },
        {
            "name": "code",
            "valueString": "386661006"
        },
        {
            "name": "result",
            "valueBoolean": true
        }
    ]
}
`

**Comment by yunwwang** [comment]
Could you run test again? I don't see the issues for validation code in us-ocre-condition-code value set this morning.

Also the error message `Unable to resolve value set "http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code|4.0.0"` makes me wonder if this is a glitch on tx.fhir.org since it is the terminology server's work to resolve a valueset.

Please let me if you see the same error today.

**Comment by fpivonka** [comment]
> Could you run test again? I don't see the issues for validation code in us-ocre-condition-code value set this morning.
> 
> Also the error message `Unable to resolve value set "http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code|4.0.0"` makes me wondering if this is a glitch on tx.fhir.org since it is the terminology server's work to resolve a valueset.
> 
> Please let me if you see the same error today.

@yunwwang I am seeing the same error today with this test I just ran https://inferno.healthit.gov/suites/test_sessions/c1c90b9c-f2f6-499e-9200-da6daeade7be#us_core_v400-us_core_v400_condition

**Comment by yunwwang** [comment]
This is strange. I imported the first failed Condition into my local reference server and runs on my local dev environment using the same validator on inferno.healthit.gov. I could not reproduce the error.

**Comment by fpivonka** [comment]
Did you try this condition? I suspect it has something to do with the multiple condition.codes we are returning. 2 of the codes are valid but I'm sure the IMO condition.code is not 

` 
   {
      "fullUrl": "https://fhir-ehr.cerner.com/r4-beta/17316440-14fe-4957-b62f-9d85de2c88ca/Condition/d193243229",
      "resource": {
        "resourceType": "Condition",
        "id": "d193243229",
        "meta": {
          "versionId": "193243229",
          "lastUpdated": "2021-12-08T17:33:36.000Z"
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Condition</b></p><p><b>Patient</b>: SKYWALKER Jr, ANIKAN G</p><p><b>Diagnosis</b>: Routine physical examination, Routine physical examination</p><p><b>Category Classification</b>: Medical</p><p><b>Clinical Status</b>: Active</p><p><b>Verification Status</b>: Confirmed</p><p><b>Onset</b>: Dec  8, 2021</p></div>"
        },
        "clinicalStatus": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
              "code": "active",
              "display": "Active"
            }
          ],
          "text": "Active"
        },
        "verificationStatus": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
              "code": "confirmed",
              "display": "Confirmed",
              "userSelected": false
            }
          ],
          "text": "Confirmed"
        },
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/condition-category",
                "code": "encounter-diagnosis",
                "display": "Encounter Diagnosis"
              }
            ],
            "text": "Encounter Diagnosis"
          },
          {
            "coding": [
              {
                "system": "http://snomed.info/sct",
                "code": "74188005",
                "display": "Medical (qualifier value)",
                "userSelected": false
              }
            ],
            "text": "Medical"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://e-imo.com/products/problem-it",
              "code": "515673",
              "display": "Routine physical examination",
              "userSelected": false
            },
            {
              "system": "http://snomed.info/sct",
              "code": "310366008",
              "display": "Medical examinations/reports status (finding)",
              "userSelected": false
            },
            {
              "system": "http://hl7.org/fhir/sid/icd-10-cm",
              "code": "Z00.00",
              "display": "Encounter for general adult medical examination without abnormal findings",
              "userSelected": false
            }
          ],
          "text": "Routine physical examination"
        },
        "subject": {
          "reference": "Patient/4755812",
          "display": "SKYWALKER Jr, ANIKAN G"
        },
        "encounter": {
          "reference": "Encounter/4505393"
        },
        "onsetDateTime": "2021-12-08",
        "recordedDate": "2021-12-08T17:33:36.000Z",
        "recorder": {
          "reference": "Practitioner/3915780",
          "display": "Lewis M.D., Mark"
        }
      },
      "search": {
        "mode": "match"
      }
    },
`

**Comment by yunwwang** [comment]
Yes. This resource passed validation test also. 
![image](https://user-images.githubusercontent.com/8761175/185470411-41cb8c51-6f25-4992-b3ff-dc190df21eff.png)
![image](https://user-images.githubusercontent.com/8761175/185470474-1b5f98b0-eb47-4e90-a1e0-88a6196afcf9.png)

I don't think it is multiple coding issue. The error message is pretty that the terminology server does not understand that url. That is a standard canonical url with version attached so I don't understand why terminology server failed to resolve it.

**Comment by fpivonka** [comment]
Ok, we tried it in 'dev' and it passes https://inferno-dev.healthit.gov/suites/test_sessions/69b2e7c5-0873-4acb-8641-86bd8bf077aa#us_core_v400-us_core_v400_condition

then also tried in 'prod' again -and it fails as it has in other runs.  https://inferno.healthit.gov/suites/test_sessions/9ecf6830-88c2-4a9a-b642-0d4c0568a627#us_core_v400-us_core_v400_condition

**Comment by fpivonka** [comment]
@yunwwang any updates on this? is the fact that it passed in 'inferno-dev' mean that this issue will be resolved in prod in the future?

**Comment by yunwwang** [comment]
I noticed that this issues popped up on again. Here are some background information.

==========

Inferno test kits use Inferno validator service for all validation. The validator server for g10 test kit uses local terminology service. The validator for US Core uses tx.fhir.org/r4 for terminology validation.

The Inferno validator service is a service wrapper around https://github.com/hapifhir/org.hl7.fhir.core. Other than kick start a web service, the wrapper does not add many additional logic there.

During the validation, Inferno send the FHIR resource and target profile's canonical url to the inferno validator service and service wrapper initializes the validator engine in hl7.fhir.core to run the validation.

==========

We have verified that the error does not pop up on (g)(10) Test Kit with US Core v4.0.0/v5.0.1. It only appears on US Core test kits. Now we have seen that on all three version of US Core test kit.

Inferno does not call tx.fhir.org to do code validation directly. Instead, it is the validator engine (https://github.com/hapifhir/org.hl7.fhir.core) which requests $validate-code to the terminology server. We did a code inspection of related classes in hl7.fhir.core. We noticed when validator engine calls terminology server, it sends the whole valueset instead of just canonical url. That means the canonical url in the error message `http://hl7.org/fhir/us/core/ValueSet/us-core-condition-code|4.0.0` was generated inside tx.fhir.org.

Our initial conclusion is that some kind of caching, either at tx.fhir.org or in hl7.fhir.org classes, caused this strange issue.

I suggest to run a trial testing using (g)(10) Test Kit with US Core v4.0.0 on inferno-dev to make sure the error is not shown.

We will have a new release for SVAP by the end of this month.
