### ISSUE TITLE
(g)(10) Standardized API US Core 4.0.0 - Smoking Status Observation Search by Category

### ISSUE THREAD

**Issue by yashpalk** [onc-healthit/onc-certification-g10-test-kit#257]
For Smoking Status Observation resources, is search by patient + category required? Noticed that the new version of Inferno is testing for this, but we didn't see it as a mandatory search parameter on the profile page: https://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-smokingstatus.html#mandatory-search-parameters

**Comment by arscan** [comment]
Good catch @yashpalk.

I believe our logic for determining what searches are required for a profile is to start with the mandatory search combinations for the resource type defined the capability statement (In this case, [Observation](http://hl7.org/fhir/us/core/STU4/CapabilityStatement-us-core-server.html#observation)), and then remove any search combinations that include an element that the profile does not mark as either 'must support' or mandatory (cardinality >= 1).

In v3.1.1 (and earlier), this lined up exactly with the search in the 'Quick Start' section of each profile.  Apparently in v4.0.0+ for SmokingStatus, that isn't the case any more.  Category is flagged as must support for that profile, and they must include a fixed code, and yet that isn't a mandatory search parameter.

@yunwwang does that explanation look right to you?  Should we follow up with the US Core group to understand what the logic is for the quick start mandatory searches for a profile?  We could hard-code an exception here, but it is nice for the required supported searches to follow some logic that can be derived from machine-readable information.

**Comment by yunwwang** [comment]
I think this is a bug in US Core v4.0.0. `Observation.category` was changed from `optional / not must support` in v3.1.1 to `required / must support` in v4.0.0. Apparently, the "Quick Start" narrative section was not updated to reflect such change.

I will create a JIRA ticket for CGP.

**Comment by arscan** [comment]
@yunwwang I'm not sure if the fact that it is now `required/must support` necessarily means that the search param combo of `patient+category` needs to be supported, unless they wrote that rule down somewhere.  So it might not be a bug.  But it's worth raising to see what the general rule is for that Quick Start section.

Also, since that category slice isn't specific to this type of resource, you'd expect that patient+category search to perhaps return more than smoking status coded resources, which would violate a different expectation we have for these Observation searches.  So even if this is a 'bug' in the spec, I think we are going to have to make some kind of change, right ([specifically here](https://github.com/inferno-framework/us-core-test-kit/blob/200f3d2651995c23cb04cfa38e49d4122440fc28/lib/us_core_test_kit/search_test.rb#L109) if that search is supposed to stay).

**Comment by yashpalk** [comment]
Thanks both! Would you mind posting the JIRA link here as well so we can follow along with the discussion?

**Comment by yunwwang** [comment]
https://chat.fhir.org/#narrow/stream/179190-united-states/topic/Search.20Parameter.20for.20SmokingStatus

**Comment by arscan** [comment]
@yashpalk In the above Zulip thead, a [US Core author said](https://chat.fhir.org/#narrow/stream/179190-united-states/topic/Search.20Parameter.20for.20SmokingStatus/near/298006892) that the searches listed in the Quick Start section of the profiles may not be a complete list of mandatory searches, and you must review the [US Core Server CapabilityStatement](https://hl7.org/fhir/us/core/STU4/CapabilityStatement-us-core-server.html) to determine the full set of [searches that must be supported for the associated Resource type](https://hl7.org/fhir/us/core/STU4/CapabilityStatement-us-core-server.html#observation).

Our tests are set up to only make profile-specific queries where we know the system must support the element being searched on for that type of data, and in US Core v3.1.1 the `category` element did not need to be supported on Smoking Status Observation resources, so we didn't include it.  Starting in v4.0.0, that element now must be supported.  So it seems to make sense to have this be tested to me.

Does this make sense?

@yunwwang -- I did notice that we don't search by `patient+category+date` though, and that seems to be a bug on our side (perhaps based on changes to structuredefs and slicing for other types of observations?)

**Comment by yunwwang** [comment]
Yes. That is bug in our code generator. The issue is that SmokingStatus has sliced the element `Observation.effective[x]` to `Observation.effective[x]:effectiveDateTime`. The `date` search parameter has expression `Observation.effective` while what code generator is looking for is `Observation.effectiveDateTime`. Will fix this.

**Comment by yashpalk** [comment]
The explanation makes sense. Appreciate the help with the clarification!

Just echoing what you mentioned in the Zulip thread, it's unintuitive that the profile page does not list all of the search parameters that are required for a given profile under the section that is titled **Mandatory Search Parameters**.

**Comment by claudia-flatiron** [comment]
@arscan, added notes to Zulip chat requesting more clarity on mandatory search capabilities
...RE: It would have been very helpful to me and the development team that relied on my interpretation and guidance to know that the "Mandatory Search Parameters" section might be incomplete for a given profile. I understand now to go to the capability statement as a source of truth, but either of these approaches would also be beneficial in the future, for example to people still learning all the internal logic of the IG, and to product managers and others who need to understand scope and for whom the more narrative spec is very useful.

**Comment by yunwwang** [comment]
Patient + category search is implemented in v3.2.0 (PR shown above). Ticket closed.
