### ISSUE TITLE
Inferno Public Instance Having Issues

### ISSUE THREAD

**Issue by darena-pjindal** [onc-healthit/onc-certification-g10-test-kit#281]
Is the Inferno public site having issues? It shows the error below
![image](https://user-images.githubusercontent.com/45796558/192152265-1cefc610-88d6-4cab-a257-8253a8a080e1.png)

**Comment by arscan** [comment]
Thanks for letting us know.  Turns out in this case this was a false alert -- the error message was generated when the test service temporarily couldn't connect to a separate validator service when the test service was last cycled, but the error message was never cleared out when the validator service came up.

We cleared out the message and verified that the tests are functioning properly.  Please let me know if you are seeing anything odd from your end.

**Comment by darena-pjindal** [comment]
Thank, @arscan . Appreciate the quick response on a Sunday.
