### ISSUE TITLE
Getting No SMART extensions found in CapabilityStatement!

### ISSUE THREAD

**Issue by joshuaasm** [onc-healthit/onc-certification-g10-test-kit#292]
We are getting "No SMART extensions found in CapabilityStatement", though we have everything as per the documentation. Please advice if we missed anything. Attaching the error details and our actual capabilityStatement json for your reference.

We are using Inferno 3.0.1 Version:

ONC Certification (g)(10) Standardized API - US Core 3.1.1 / USCDI v1, SMART App Launch 1.0.0, Bulk Data 1.0.1
V.3.0.1

![No_Smart_extensions_found_issue](https://user-images.githubusercontent.com/115110649/194143013-50c2d9d0-ddcd-4707-a728-a711d02ee082.png)
[capability_statement.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9718380/capability_statement.txt)

**Comment by arscan** [comment]
Since your capability statement is very nearly identical to the one our reference/demo server uses (inferno.healthit.gov/reference-server/r4/metadata), and our server passes this test, something strange is going on.

Just to be certain, when you look at the request details for the /metadata request in the test interface, the response from your server that inferno received is exactly the one that you pasted as an attachment?

e..g

![Screen Shot 2022-10-05 at 4 04 17 PM](https://user-images.githubusercontent.com/412901/194153325-5f0dbb61-9928-4c20-8831-7a112e851c0a.png)

**Comment by joshuaasm** [comment]
yes, we made sure to be as identical as reference/demo server version except the base, authorize, token, revoke endpoints were our  QA endpoint server context.  We also tried with our older version very similar, which we didn't feel anything wrong with also failed, so we tried to be as identical as reference/demo-server (except our QA domain endpoint references). Attaching the response header also, just for your reference.
![response_header_v1](https://user-images.githubusercontent.com/115110649/194154986-f2c92713-24e2-4ca7-b6ae-07e668e3b28a.png)
Attaching, prior to making very identical to reference/demo-version. We don't feel this version also doesn't seem to be wrong. But we tried by making as identical as reference server's version, still no luck. Any advice will be very helpful.
[qa_capability_statement_v1.txt](https://github.com/onc-healthit/onc-certification-g10-test-kit/files/9718752/qa_capability_statement_v1.txt)

**Comment by arscan** [comment]
One difference on this second qa capability statement that may make a difference is the code you use for the security service is 'SMART-ON-FHIR' while we match on 'SMART-on-FHIR'.  Since a system could have multiple Capability.rest elements (it is an array), we look across all of them and use the one that has the CapabilityStatement.rest.security.service.coding.code == 'SMART-on-FHIR' to then pull out the various endpoints from there.

https://github.com/inferno-framework/smart-app-launch-test-kit/blob/e3833d63d03f30a75ab945e7cebb1f97dad0027c/lib/smart_app_launch/discovery_stu1_group.rb#L73-L92

The first one you sent doesn't have this problem though.

**Comment by joshuaasm** [comment]
@arscan  Thank you much, That "SMART-on-FHIR" was the key, everything else was same except that was mismatched with "SMART-ON-FHIR" (Case sensitive.)  I am closing this question with your answer. Thanks!
