### ISSUE TITLE
Failing to query pediatric patient ID

### ISSUE THREAD

**Issue by drtootsie** [onc-healthit/onc-certification-g10-test-kit#346]
https://inferno.healthit.gov/suites/test_sessions/607472d3-f2c1-44c5-ac12-1ffcc05426a8#g10_certification-g10_single_patient_api

Is there any reason why on my pediatric tests the secondary ID isn't being used to query for the pediatric data?  My first ID is my adult patient, and the second ID is my pediatric patient, but only the former is queried.

**Comment by yunwwang** [comment]
This is caused by an error on the first search. Inferno queries `https://fhirtest.netsmartcloud.com/uscore/v1/Observation?code=77606-2&patient=706` but the Observation resources in the result Bundle not contain code '77606-2'

If the server does not have any resources matching the search query, server shall return a Bundle with empty result.
