### ISSUE TITLE
Medication ruby error showing

### ISSUE THREAD

**Issue by drtootsie** [onc-healthit/onc-certification-g10-test-kit#352]
https://inferno.healthit.gov/suites/test_sessions/521c02d6-58f0-40f7-8ad1-a12031f79565#g10_certification-g10_single_patient_api

For some reason, we started getting the following error that looks like it's pointing to some ruby issue?  Is this a big or are we populating something wrong. We have one team passing, and one failing on this. 

4.13.04 Server returns Provenance resources from MedicationRequest search by patient + intent + revInclude:Provenance:target Error: wrong constant name 000153         candidate = constant.const_get(name)                            ^^^^^^^^^^ /usr/local/bundle/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:288:in `const_get'

**Comment by Jammjammjamm** [comment]
That error indicates that there is something in a resource which is preventing it from being parsed as a FHIR resource. In this case I'm pretty sure there's a reference that can't be understood.

A reference is expected to be in the format `base_url/resource_type/id/version`, with `base_url` and `version` being optional. There is some reference which is built in such a way that `000153` is in the position where the `resource_type` should be. So instead of looking up something like `FHIR::Patient`, the code tries to look up `FHIR::000153`, which is not a valid FHIR resource type, so it fails.

**Comment by drtootsie** [comment]
That was it!!  Thank you!
