### ISSUE TITLE
US Core 3.1.1 _search GET requests without parameters

### ISSUE THREAD

**Issue by KoyFoster** [onc-healthit/onc-certification-g10-test-kit#396]
I've bee reading that in US Core 3.1.1 that the _search requests are suppose to be GET requests that use parameters. The GET part is true, however it seems that the tests are still trying to pass the parameters around like it's a POST, using a body. 

Is this a bug or am I crazy and misreading something somewhere? This is big blocker for me.

![image](https://user-images.githubusercontent.com/12465882/215601642-b4d7efca-3f1f-4775-a9ea-22175b043c5b.png)
![image](https://user-images.githubusercontent.com/12465882/215601817-4f70e290-68e4-4572-b8a2-ef40035d9ca3.png)

**Comment by arscan** [comment]
The ABOUT section of the test states:

> Additionally, this test will check that GET and POST search methods return the same number of results. Search by POST is required by the FHIR R4 specification, and these tests interpret search by GET as a requirement of US Core v3.1.1.

It's confusing, but the base fhir specification requires support for search by post, but doesn't require support for search by get. Since we test requirements from base fhir as well as any added requirements in US Core, and US Core cannot loosen restrictions proved in the base fhir specification, we check for support for search by post (from base fhir) and get (added in us core). Later versions of US Core clarify this by explicitly stating search by post and get are both required. They aren't adding the requirement for support for search by post, they are simply restating it for clarity.

Does this help? Let me know if I'm misinterpreting your question.

**Comment by KoyFoster** [comment]
It totally sounds like I had it backwards. I think this, and the developer intent behind the the code I'm trying to revive had me mixed up. Thanks a lot.
