### ISSUE TITLE
Multi patient API test failing without waiting for the specified export wait timeout (550 seconds). (FI-1959)

### ISSUE THREAD

**Issue by madhavdarji** [onc-healthit/onc-certification-g10-test-kit#420]
I initiated a multi patient API test and it immediately failed without waiting for the specified export wait time (550 seconds).

Below is 1 test instance.
https://inferno.healthit.gov/suites/g10_certification/a3dTZQ84PNE#g10_certification-multi_patient_api

**Comment by arscan** [comment]
Hi @madhavdarji --

It appears that the initial polling status request returns the following header:

```
Retry-After: 7200
```

Per [the spec](https://build.fhir.org/ig/HL7/bulk-data/export.html#bulk-data-status-request), this means the client should wait 7200 seconds (2 hours) before hitting the polling location again to ask for status.  Is this intentional?  My assumption is the test sees this and notes that it is beyond the max export time threshold that we set to avoid bogging down the test system with a lot of long-running exports, and therefore stops the test.

**Comment by madhavdarji** [comment]
Did anything change in Inferno side as the Retry-After value hasn't changed on our side. Additionally when I tested the same (see below screenshot), the parameter value was 120 (2 minutes).

![2023-03-30 19_43_15-https___fhir4 eclinicalworks com_fhir_r4_JAFJCD_Group_ba542a09-9f1a-44f9-943a-da](https://user-images.githubusercontent.com/23702849/228988674-95de3e57-b9de-447d-b8fe-46d41868be9b.png)

**Comment by yunwwang** [comment]
Hi @madhavdarji: The `retry-after` header is sent by bulk data server to inform bulk data client when to get export status.

Do you still experience the same timeout issue? The test session in your first post was already shown success for test 7.2.05

**Comment by madhavdarji** [comment]
Hi @yunwwang, The Inferno tool (test#7.2.05) is immediately failing without waiting for the specified export wait time.

Hi @arscan, Can you please confirm in which request is the server returning 7200 in **Retry-After** parameter? Additionally, what's the purpose of the **Export Times Out after (1-600) (required)** configuration parameter if the Inferno tool is relying on the Retry-After parameter

**Comment by yunwwang** [comment]
The session you provided in your first post shows a pass

![image](https://user-images.githubusercontent.com/8761175/229194737-87586b35-39f1-444b-a083-133dad608726.png)

Can you create a new test session so we can investigate the series of events again?

Inferno calculates if the next retry exceeds the specified time out input. For example, if the time out is 180 seconds and retry after is 120, then Inferno times out after 1 retry because the 2nd retry is at 120 + 120 = 240 seconds after the initial request which is over 180 time out setup.

**Comment by yunwwang** [comment]
I can confirm the `retry-after` is 7200. See screen shot for response header:

![image](https://user-images.githubusercontent.com/8761175/229211763-79da97f3-8477-48a1-997d-7a8a4ef966ce.png)

**Comment by arscan** [comment]
Hi @madhavdarji -- See the response from the polling status endpoint in 7.2.05

![Screenshot 2023-03-31 at 3 25 58 PM](https://user-images.githubusercontent.com/412901/229211930-23d9200e-0a95-4df4-9d5f-41921c836b6b.png)

So, we hit the status polling endpoint, in which your server says that the export isn't done but come back in 7200 seconds (2 hours) to ask again.  Our client's logic is set up to check to see when that 'come back' date is, but since it is too far in the future it stops.

https://github.com/onc-healthit/onc-certification-g10-test-kit/blob/937ff9b772744c8cbece254621dfe36cc48af2c2/lib/onc_certification_g10_test_kit/bulk_data_group_export_stu1.rb#L204-L216

Does that make sense?  If your exports can never complete in under 10 minutes in a test environment, which is the max duration we currently allow, we can discuss extending that.  But I just want make sure that the 2 hour retry time is intentional first.

**Comment by yunwwang** [comment]
The same logic was used in Inferno Program edition since v1.0.0 which was released on June 2020.

**Comment by madhavdarji** [comment]
Thanks @yunwwang for confirmation. Any comments on the 2nd point?

**Comment by yunwwang** [comment]
Sorry, what do you mean by "he error reported is corrected". I may lost the context.

**Comment by arscan** [comment]
I think @madhavdarji's point is that the error message "Server took more than 550 seconds to process the request." is confusing and could be improved.  The test did not technically wait 550 seconds, but rather took the server at it's word that it wouldn't be done for at least 7200 seconds (which is what the 'Retry-After' header sent by the server means) so it gave up immediately because that is well beyond the 550 second maximum run time for the test (which is something the tester can configure via input).

We could update the test such that the error message is more precise (e.g. 'Server polling endpoint provided a `Retry-After` header of 7200 seconds, which is beyond the remaining allowed run time of the test of 550 seconds'), or have the test try one poll attempt at the very end of the timeout to see if the export is done.

Do you think either of those would solutions would have helped avoid this confusing @madhavdarji?  Or am I misunderstanding what your issue?

**Comment by madhavdarji** [comment]
> Do you think either of those solutions would have helped avoid this confusion @madhavdarji?

You are correct, that's what I meant @arscan.
