### ISSUE TITLE
Inferno claiming 'M54.51' does not exist in http://hl7.org/fhir/sid/icd-10-cm

### ISSUE THREAD

**Issue by KevinCranmer** [onc-healthit/onc-certification-g10-test-kit#424]
We are getting the following test failure on section 7.12 for the US Core 5.0.1 Test Suite:

> Condition/I2-E5XG7RTZ434JUUTKMS62TZW5ZI000000: Condition.code: Local Error: Resolved system http://hl7.org/fhir/sid/icd-10-cm (v2.0.0), but the definition is not complete. Server Error: The code "M54.51" is not valid in the system http://hl7.org/fhir/sid/icd-10-cm; The code provided (http://hl7.org/fhir/sid/icd-10-cm#M54.51) is not valid in the value set 'USCoreConditionCodes' (from http://tx.fhir.org/r4)

A list of codes that failed (and don't appear in https://icd.codes/icd10cm):

- M54.51
- F43.89
- R05.9
- Z20.822

I have a hunch that wherever inferno is pulling the list of codes may be out of date. Because both https://icdlist.com/ and https://www.icd10data.com show all 4 of those codes as existing and valid.

This is likely another instance of the already known issue: https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/FAQ#q-why-do-some-resources-fail-in-us-core-test-kit-with-terminology-validation-errors. But the FAQ still requests I submit the issue here so that an issue can be created for the terminology server.

**Comment by yunwwang** [comment]
@KevinCranmer Thank you for raising this issue. We want to verify if the validation is caused by Inferno or terminology server before escalate the question to terminology work group.

I tried this on tx.fhir.org:

http://tx.fhir.org/r4/CodeSystem/$validate-code?code=M54.51&system=http://hl7.org/fhir/sid/icd-10-cm

Such request returns

![image](https://user-images.githubusercontent.com/8761175/233161605-aaa0b9c8-925d-4001-83f9-6f1968f90497.png)

I have create a thread on zulip: https://chat.fhir.org/#narrow/stream/179202-terminology/topic/ICD-10.20validation.20error

**Comment by KevinCranmer** [comment]
Thank you for the response! I looked at a 3 different websites that list the icd 10 cm codes, 2 of which showed the code as valid, and one of which did not have the code existing. Not sure where the real source of truth lies.
