### ISSUE TITLE
Inferno uses additional patients with same token

### ISSUE THREAD

**Issue by Nbhatin** [onc-healthit/onc-certification-g10-test-kit#431]
Using reference Server for inferno g10 Certification suite.
I select/authorize patient 85 through standalone tests.

Noticed that while running single patient tests, it uses the same token ( generated for patient id 85) to access resources for both patient 85 and 355 (Additional patient).

Trying to understand why it did not fail for 355 since the user did not pick /authorize permissions for this patient.

**Comment by arscan** [comment]
For a real system, this shouldn't work.  The reason is simply that our reference server isn't a real system, and there are shortcuts to make it a bit easier to demonstrate the tests quickly.  For example, we don't require user logins to access the reference server, which is something that would occur on a real system.  In this case, its nice to be able to run the Standalone Patient App test, then hop down to the Single Patient API tests and using the same token see that run.  But our test data is shaped in such a way to ensure that you could use multiple patients to satisfy the 'must support' checking, which isn't possible when only one patient is launched.

Having said that, it does seem like having a negative test that ensures this unrealistic behavior isn't used might be worthwhile.  We have other tests to ensure that unauthorized requests fail appropriately, but in this situation we do not.

Adding this test, and increasing the fidelity/realism of the reference server so that test would still pass, would likely require us to reorganize the tests somewhat, or change our demonstration test data to satisfy the must support requirements on a single patient.  We could consider doing that in a future major release if that specific check is desired.

**Comment by Nbhatin** [comment]
Thanks for the response.

**Comment by arscan** [comment]
> So, on the single patient API Tests, it requires PatientID ( from smart app) and additional Patient ID ( that together with patientID from smart app contains must support fields)

The 'Additional Patient IDs' field is optional and is provided in the event that systems cannot realistically have a single patient that satisfies all must support requirement.  We spread the must support requirements across 2 patients on our 'reference server' just for demonstration purposes, though we could update our test data to have everything under a single patient. We like having it spread across two to ensure this more complex logic of checking must-support logic across multiple patients is always properly maintained.  But it does expose an unrealistic situation if you test out-of-order.

> Would you know if FHIR allows returning multiple patientIDs in standalone launch ?

No, only a single patient can be 'in context'.

The realistic situation that would use the Additional Patients field is for a token with 'User Scopes' (access to all patients that a user has access to), which is the scope of the access token granted in step 3 "EHR Practitioner App".  That test requires system to demonstrate that there is a patient in context too, and therefore a single patient is returned from the launch, but providing a patient in context does not mean that access is limited to only that patient.  f you wanted to limit to just the patient in scope, only Patient-level scopes would be granted.

To try that out on the inferno reference / demo server, see the instructions in the walkthrough: https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/Walkthrough#step-5-perform-ehr-practitioner-app-tests

Originally, we considered locking down the 'Single Patient API' tests to only use a User-level scope granted from the EHR Launch, but we decided to just allow systems to use a token from the Standalone Launch too for convenience, because the EHR launch can be somewhat burdensome because it involves navigating to another site to simulate the EHR launch.  But, if you use the 'Additional Patients' field you shouldn't use the Standalone Launch.

Does this help?  I understand that allowing users to fill in the 'Additional Patients' field while using a 'Patient-level scope' token might be confusing because it shouldn't be possible in a real system.

Also, one thing to keep in mind is that these tests, at their core, are intended to check for interoperability in the API and authorization processes so that clients could rely on a standard interface across different health IT services.  They don't truly verify that a service is 'secure', that is a very different problem.  Over time though, we've added some security checks that were deemed to be critical because they exposed common, non-obvious and dangerous mistakes that servers could make.  Perhaps adding a test to ensure that patient-scoped tokens are only allowed access to a single patient id would be considered critical, but if we went down that path we could justify adding a lot more security-related tests.
