### ISSUE TITLE
g10 test suite doesnt validate display name for the codings

### ISSUE THREAD

**Issue by Nbhatin** [onc-healthit/onc-certification-g10-test-kit#441]
I am running conditions tests and the condition has a garbage value in clinicalStatus.coding.display

 "clinicalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
                "code": "resolved",
                "display": "Viral sinusitis (disorder)"
            }
        ]
    },
    
g10 test suite - did not show any error/warning for incorrect display although it is a required binding.
uscore 3.1.1 test suite gave a warning that display is not correct
https://inferno.healthit.gov/validator/results - gave warning : Condition.clinicalStatus: Display Name for http://terminology.hl7.org/CodeSystem/condition-clinical#resolved should be 'Resolved', not 'Viral sinusitis (disorder)'

Is there a bug in g10 suite that it doesnt validate display for any coding ? I expect to see warning on this suite just like uscore3.1.1 and public validator.

**Comment by yunwwang** [comment]
(g)(10) test suite is designed to not throw warnings for mismatched display. The reason behind that is warning does not affect the pass/fail of a test. Too many warning messages add confusion and could cause testers/implementers lose theirs focus on the "real" issue, those error messages.

**Comment by Nbhatin** [comment]
is it not supposed to throw an error if display fails the terminology validation ?

**Comment by yunwwang** [comment]
Our terminology validation tests for (g)(10) certification do not currently consider display differences a 'failure', which until very recently matched the behavior of the HL7 FHIR Validator coupled with [tx.fhir.org](http://tx.fhir.org/).  See [this thread on zulip](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Display.20name.20issues.20as.20warnings.20vs.2E.20errors) for a discussion.  We tend to be conservative in the (g)(10) certification tests because we absolutely do not want to enforce any requirements that may not exist or may not apply in this context.  However, this behavior change from the Hl7 FHIR Validator is causing us to take a look at this again, and we may update our tests to now consider this a failure.  There is a SHALL requirement in the specs [here](http://hl7.org/fhir/R4/datatypes.html#Coding) regarding this.  But it will be a  large change so this is something that will likely take some time to implement and socialize.  We do encourage people to try out the US Core tests outside the context of g10 certification to help them identify any of these kinds of problems, as those tests proactively bring up things that MIGHT be issues but may not be.
