### ISSUE TITLE
Pulse Oximetry 3.1.1 test validation

### ISSUE THREAD

**Issue by medhost-bfindeisen** [onc-healthit/onc-certification-g10-test-kit#443]
Test 4.18.06 - Observation resources returned during previous tests conform to the US Core Pulse Oximetry Profile

Based on the 3.1.1 profile 
http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-pulse-oximetry.html

We expected a check for code 59408-5 but Inferno is checking for both 59408-5 and 2708-6 to be present in the code section.

**Comment by yunwwang** [comment]
us-core-pulse-oximetry profile is based on FHIR oxygensat profile (http://hl7.org/fhir/R4/oxygensat.html). So a resource has to conform to constraints from both profile. 

Instead of reading the "Differential View", look at the "Full View" which indicates that both codes are required:

![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/8761175/6bdce068-913a-408a-a4f2-d092a6bac8b4)

**Comment by medhost-bfindeisen** [comment]
Thanks for the clarification

**Comment by medhost-gkersting** [comment]
@yunwwang Another question. In our data we have an Observation with 59408-5, an Observation with 2708-6 and then one that has the panel of 59408-5 and 2708-6. It appears that for the Observations with one LOINC code this test is also picking those up those and thinking they should also have both codes. Is that correct?

**Comment by yunwwang** [comment]
Because US Core Pulse Ox profile is based on FHIR Ox Sat profile, all US Core Pulse Ox observations are also FHIR Ox Sat observation, but not vise versa. That is same to say that US Core Pulse Ox observations are a subset of FHIR Ox Sat observations. 

It means that all observations with code 59408-5 (US Core Pulse Ox) shall also have code 2708-6 (FHIR Ox Sat) but observation with code 2708-6 may or may not have 59408-5. 

"It appears that for the Observations with one LOINC code this test is also picking those up those and thinking they should also have both codes." This is true for those with code 59408-5.

Tests in 4.18 (Pulse Ox) shall not deal with any observation having code 2708-6 only. If there is such observations (having 2708-6 only), please double check the server response in test 4.18.01. Server shall not return such observations.
