### ISSUE TITLE
Could not find Observation.specimen error but specs say otherwise (FI-2312)

### ISSUE THREAD

**Issue by ivanquan8** [onc-healthit/onc-certification-g10-test-kit#469]
Hello. We're testing our FHIR server against the newly released inferno US Core v6.1 and getting an error for observation lab result profile specifically for element Observation.specimen. The FHIR USCv6.1 spec states, "The specimen type can be communicated in the mandatory Observation.code (e.g., Blood Glucose), or the Must Support Observation.specimen element, or through both elements."

Issue:
Inferno test 10.18.07 does not align with USC 6.1 FHIR specifications for Lab Result Observation Profile.

Error message:
"Could not find specimen in the 9 provided Observation resource(s)" specifically for test 10.18.07. We tested on the public inferno server, https://inferno.healthit.gov/suites/g10_certification/d8JwNeABhI7#10

**Comment by yunwwang** [comment]
Hello @ivanquan8

I had a discussion with US Core author, Eric Haas, today. Can you create a JIRA ticket for US Core v6.1.0 so that US Core authors and other community members could weigh in the correct interpretation. You can find the link "propose a change" at the bottom of US core profile page:

![image](https://github.com/onc-healthit/onc-certification-g10-test-kit/assets/8761175/94ff803a-8e87-420a-ae3d-65a34edc02fd)

or you can go to https://jira.hl7.org directly.

**Comment by ivanquan8** [comment]
Ok @yunwwang . Just did that and the JIRA ticket link is here https://jira.hl7.org/browse/FHIR-43171

**Comment by yunwwang** [comment]
This ticket was rejected / "Not Persuasive" by HL7 CGP work group today. Attendees asserted that Server implementation must support Observation.specimen for this profile. 

Ticket closed.
