### ISSUE TITLE
"1.1.04 OAuth 2.0 Endpoints in the conformance statement match those from the well-known configuration" fails on INFERNO version V.2.0.0

### ISSUE THREAD

**Issue by dileeprt** [onc-healthit/onc-certification-g10-test-kit#53]
"1.1.04 OAuth 2.0 Endpoints in the conformance statement match those from the well-known configuration" fails on INFERNO version **V.2.0.0**

![image](https://user-images.githubusercontent.com/70513754/159728273-f152bc08-41a5-4ba7-b355-95f1a5c8e822.png)

However the same test is passing with the very same FHIR server when running against INFERNO version **1.9.0**
![image](https://user-images.githubusercontent.com/70513754/159728744-dd3b788d-4b0d-470b-b96d-842ed37153c5.png)

Could you please let us know what could be the issue.

**Comment by yunwwang** [comment]
Hello @dileeprt 
[SMART App Launch IG section 1](http://hl7.org/fhir/smart-app-launch/1.0.0/conformance/index.html#smart-on-fhir-oauth-authorization-endpoints):

The server SHALL convey the FHIR OAuth authorization endpoints that are listed in the table below to app developers. The server SHALL use both:
1. A [FHIR CapabilityStatement](http://hl7.org/fhir/smart-app-launch/1.0.0/conformance/index.html#using-cs)
2. A [Well-Known Uniform Resource Identifiers (URIs)](http://hl7.org/fhir/smart-app-launch/1.0.0/conformance/index.html#using-well-known) JSON file.

to declare its SMART authorization endpoints. (Note that we require both because the specification is transitioning away from CapabilityStatement, but needs to preserve compatibility with existing implementations.)

1.1.04/OSD-05 is to verify that server does expose its endpoints at both location. Inferno 1.9 (OSD-05) used to verify only the "SHALL/required" endpoints. Inferno 2.0 expands its testing to include "SHOULD/optional" endpoints also. This is following the author's intention of section 1 that a client can get all endpoints server provides from either location. Exposing an endpoint (required or not) in one location but not the other would cause confusion at client side.

From the error message you posted, we can see that the well-known JSON does not have registration endpoint. So if you do want to expose registration endpoint, you shall expose in both well-known JOSN and CapabilityStatement

**Comment by arscan** [comment]
Thanks for highlighting that this test has changed behavior since v1.9 @dileeprt -- that should be documented.  We will update our v2.0 changelog to point out that we made this a little more strict.  Do you object to the behavior and think we should revert it in our next release, or are you simply pointing out the change?

Thanks!

**Comment by dileeprt** [comment]
Hello,
Sorry for delayed response. I just wanted to know about the change in v2.0 and it is fine, we have fixed it in our code.
